# Module: jolokia
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.6/metricbeat-module-jolokia.html

- module: jolokia
  metricsets: ["jmx"]
  enabled: true
  period: 10s
  namespace: "metrics"
  hosts: ["localhost:8080"]
  username: "jolokia"
  password: "jolokia"
  path: "/jolokia/?ignoreErrors=true&canonicalNaming=false"
  jmx.mappings:
    - mbean: 'java.lang:type=Runtime'
      attributes:
        - attr: Uptime
          field: uptime
    - mbean: 'java.lang:type=GarbageCollector,name=ConcurrentMarkSweep'
      attributes:
        - attr: CollectionTime
          field: gc.cms_collection_time
        - attr: CollectionCount
          field: gc.cms_collection_count
    - mbean: 'java.lang:type=Memory'
      attributes:
        - attr: HeapMemoryUsage
          field: memory.heap_usage
        - attr: NonHeapMemoryUsage
          field: memory.non_heap_usage
