---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haptik-tomcat
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: haptik-tomcat
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: haptik-tomcat
subjects:
- kind: ServiceAccount
  name: haptik-tomcat
  namespace: default
roleRef:
  kind: ClusterRole
  name: haptik-tomcat
  apiGroup: rbac.authorization.k8s.io
